### ISSUE TITLE
No column options for events module

### ISSUE THREAD

**Issue by jamesgiroux** [faithmade/faith-builder#1]
When adding the events module to the page, it lists all the events in a full 12 column view without any options to change the number of columns for each item.

**Comment by garand** [comment]
Can you elaborate on this a little? I'm not too familiar yet with Beaver Builder's columns.

**Comment by jamesgiroux** [comment]
Well, the way that the events display is one on top of the other.  When you've got an image in there it means that the events are wide (across the whole screen) and in my opinion, too big for the space.  There's no option at the moment to adjust the number of columns each event actually takes up in the display so a user is stuck with whatever is set by the code.

**Comment by jamesgiroux** [comment]
what that means is that there's no way to have multiple events on a single line to reduce the amount of real estate the events take up.

**Comment by garand** [comment]
Gotcha. That will be a part of the styling, but yes, I think it would be helpful to have two display modes. List and grid for instance.

**Comment by garand** [comment]
This is completed. Let me know if you want anything more comprehensive.
