### ISSUE TITLE
Look into recurring events add on and decide to add to module / post type 

### ISSUE THREAD

**Issue by angela-crist** [faithmade/faith-builder#10]

**Comment by angela-crist** [comment]
We will need to rewrite this and this exists in the Faithmade reop: https://github.com/LiftUX/faithmade/issues/47

**Comment by garand** [comment]
@angela-crist I'm going to close out both of these issues. Can you open the issue in **[faithmade/churchthemes](https://github.com/faithmade/churchthemes)**?
