### ISSUE TITLE
Will we allow the customer to create a template or start with a blank template? 

### ISSUE THREAD

**Issue by angela-crist** [faithmade/faith-builder#17]
http://lift.d.pr/ZDj6/5CaF7vlH

Thoughts @chriswallace @imbradmiller

**Comment by garand** [comment]
I would recommend prompting them to select a template, and have one of the template options be "Blank".

**Comment by angela-crist** [comment]
This was discussed in the 7/30 status meeting we will allow the customer to start with a blank layout
