### ISSUE TITLE
When saving Faith Builder images as a draft, when you preview the page it only shows the title of the page

### ISSUE THREAD

**Issue by angela-crist** [faithmade/faith-builder#18]
Is this how we want it to work? 
This is what it would look like: http://lift.d.pr/1lwz4/2GhDX8Rk

Thoughts? @chriswallace @imbradmiller @garand

**Comment by garand** [comment]
I wonder if this is a setting in Beaver Builder. We'll need to dig into their documentation, there's a chance this could be very difficult.

**Comment by angela-crist** [comment]
Closing this for now and we can revisit it if needed.
