### ISSUE TITLE
Provide a view to only show on a certain percentage of the page

### ISSUE THREAD

**Issue by angela-crist** [faithmade/faith-builder#19]
This would be needed when placing a longer text in the 'message' perhaps making it a larger text box too:
![screen shot 2015-07-15 at 2 26 00 pm](https://cloud.githubusercontent.com/assets/7047954/8706373/75b4602a-2afd-11e5-86d8-d96bbc283908.png)

![screen shot 2015-07-15 at 2 26 29 pm](https://cloud.githubusercontent.com/assets/7047954/8706388/83feac44-2afd-11e5-8526-388b656cf2cf.png)

**Comment by angela-crist** [comment]
Oh I see it wraps:
![screen shot 2015-07-15 at 2 28 16 pm](https://cloud.githubusercontent.com/assets/7047954/8706452/c682c8b6-2afd-11e5-99b1-cad071aa89cc.png)

Not sure if we want to give the option of only showing on a certain width of the page? Thoughts?

**Comment by garand** [comment]
No, that would be decided by the column that they put it in.
