### ISSUE TITLE
What is Sort 'low to high' and 'high to low' mean?

### ISSUE THREAD

**Issue by angela-crist** [faithmade/faith-builder#20]
http://lift.d.pr/1lEam/4dU4HI3g

This will need to be labeled more intuitively or educate the customer

**Comment by angela-crist** [comment]
Need to determine if we need to define what this means for the user. @garand Do you think this is needed?

**Comment by garand** [comment]
We can get rid of it. It's referring to custom post orders that can be set in the admin but I think it's too much complexity for our users.
