### ISSUE TITLE
Change location 'Show Times' to 'Service Times'

### ISSUE THREAD

**Issue by angela-crist** [faithmade/faith-builder#21]
Something that sounds more for churches:

http://lift.d.pr/18MYZ/250lM57H

**Comment by garand** [comment]
It's saying "Do you want to show the times", not talking about "show" times.

**Comment by angela-crist** [comment]
haha that's hilarious! 

![literally](https://cloud.githubusercontent.com/assets/7047954/8726567/fdc0b3e6-2ba8-11e5-88b8-7c10202a36f1.gif)
