### ISSUE TITLE
Grid Options Need To Be More Diverse

### ISSUE THREAD

**Issue by jamesgiroux** [faithmade/faith-builder#4]
I’ve jumped in and there needs to be more control over the grid option for most of these. for example, if I am choosing a number of posts to show up, that should be the number that appear in one row.  the grid at the moment is exactly the same for events, people and locations.  I’m assuming it’ll be the same for messages too.  this is great for consistency but it makes it harder to differentiate.  for example, if I want to have events and messages on the same page, because they look fairly similar in terms of their grid layout, it would be harder to visually separate them (especially if I wanted them one right after the other).  by giving me the option to choose how many items are listed in a single row, I can vary the look and feel a bit more to help different sections of the page stand out.

**Comment by angela-crist** [comment]
Is this the same issue here: #9 
If so let's close one @garand
