### ISSUE TITLE
Need More Control Over Locations Text Styles & Alignment

### ISSUE THREAD

**Issue by jamesgiroux** [faithmade/faith-builder#6]
Within the module itself it would be good to have the option to align the title as well as add a paragraph of subtext before the actual locations list.  This can be done with a text box as well so it's not the end of the world but would make for a better module, in my opinion.  Color options as well would be sweet.

**Comment by garand** [comment]
I would just have users do this with text areas if they wanted it. I don't think it falls into the scope of the locations module.
